"use client";

import { useEffect, useState } from "react";

const SERVICES = [
  "Azure AI Search",
  "Azure AI Document Intelligence",
  "Azure Container Apps",
  "Azure Key Vault",
];

export function PoweredBy() {
  const [local, setLocal] = useState(false);

  useEffect(() => {
    fetch("/api/status")
      .then((res) => res.json())
      .then((data) => setLocal(data.search_backend === "local"))
      .catch(() => setLocal(false));
  }, []);

  return (
    <div
      className="ml-auto hidden items-center gap-2 text-[11px] text-muted-foreground sm:flex"
      title={`${SERVICES.join(" · ")}. Answers generated by Gemini.`}
    >
      <span>
        Powered by <span className="font-semibold text-foreground">Azure AI</span>
      </span>
      {local && (
        <span
          className="rounded-full border border-border/60 px-2 py-0.5 font-mono text-[10px]"
          title="Local dev mode: BM25 search and a local parser stand in for Azure AI Search and Document Intelligence"
        >
          local
        </span>
      )}
    </div>
  );
}
